# Generated by Django 3.2.4 on 2021-06-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwed', '0002_rename_usercustomer_netxgen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netxgen',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='netxgen',
            name='Time',
        ),
    ]
