# Generated by Django 3.2.4 on 2021-06-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwed', '0003_auto_20210629_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netxgen',
            old_name='Customer',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='netxgen',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netxgen',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netxgen',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netxgen',
            name='interested_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='netxgen',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netxgen',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netxgen',
            name='prefered_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
